/**
 * Post-Tool Hook Handler for CLAWFORGE
 * 
 * OpenClaw has pre-tool hooks (beforeToolCallRuntime) but no post-tool hooks.
 * Claude Code has both PreToolUse and PostToolUse.
 * 
 * This module adds post-tool hooks to OpenClaw's tool execution pipeline.
 */

import { createToolHookRunner, type ToolHookDecision } from "../hooks/tool-hooks.js";

// ============================================================================
// Types
// ============================================================================

export interface PostToolContext {
  /** Tool name that was executed */
  toolName: string;
  /** Tool input as JSON string */
  toolInput: string;
  /** Tool output */
  toolOutput: string;
  /** Whether the tool execution had an error */
  isError: boolean;
  /** Session ID */
  sessionId?: string;
  /** Agent ID */
  agentId?: string;
}

export interface PostToolResult {
  /** Original tool output (possibly modified) */
  output: string;
  /** Whether this should be treated as an error */
  isError: boolean;
  /** Messages from hooks */
  hookMessages: string[];
  /** Whether a hook denied/modified the output */
  hookModified: boolean;
}

// ============================================================================
// Post-Tool Hook Runner
// ============================================================================

export class PostToolHookHandler {
  private hookRunner: ReturnType<typeof createToolHookRunner>;
  private undercoverEnabled: boolean;

  constructor(config?: {
    postToolCommands?: string[];
    undercoverEnabled?: boolean;
  }) {
    this.hookRunner = createToolHookRunner({
      postToolUse: config?.postToolCommands ?? [],
    });
    this.undercoverEnabled = config?.undercoverEnabled ?? false;
  }

  /**
   * Run post-tool hooks and merge feedback into output.
   * This is the key piece missing from OpenClaw.
   */
  async handlePostTool(context: PostToolContext): Promise<PostToolResult> {
    // Run post-tool hooks
    const hookResult = await this.hookRunner.runPostToolUse(
      context.toolName,
      context.toolInput,
      context.toolOutput,
      context.isError,
    );

    // Merge hook feedback into output (Claude Code pattern)
    let output = context.toolOutput;
    let isError = context.isError;
    const hookMessages: string[] = [];

    if (hookResult.outcome === "deny") {
      // Hook denied — mark as error
      isError = true;
      if (hookResult.reason) {
        hookMessages.push(hookResult.reason);
      }
    } else if (hookResult.outcome === "allow") {
      // Merge hook messages into output
      hookMessages.push(...hookResult.messages);
    }

    // Apply undercover sanitization
    if (this.undercoverEnabled) {
      output = this.sanitizeOutput(output);
    }

    // Build merged output (Claude Code's merge_hook_feedback pattern)
    const mergedOutput = this.mergeFeedback(output, hookMessages, isError);

    return {
      output: mergedOutput,
      isError,
      hookMessages,
      hookModified: hookMessages.length > 0 || isError !== context.isError,
    };
  }

  /**
   * Merge hook feedback into tool output.
   * Follows Claude Code's pattern: append hook messages after tool output.
   */
  private mergeFeedback(output: string, messages: string[], denied: boolean): string {
    if (messages.length === 0) {
      return output;
    }

    const sections: string[] = [];

    if (output.trim().length > 0) {
      sections.push(output);
    }

    const label = denied ? "Hook feedback (denied)" : "Hook feedback";
    sections.push(`${label}:\n${messages.join("\n")}`);

    return sections.join("\n\n");
  }

  /**
   * Strip AI indicators from output (undercover mode).
   */
  private sanitizeOutput(text: string): string {
    const patterns = [
      /Generated by (Claude|GPT|AI|agent|model)/gi,
      /As an AI (assistant|model|agent)/gi,
      /I'm an AI/gi,
      /\[ai-?generated\]/gi,
    ];

    let result = text;
    for (const pattern of patterns) {
      result = result.replace(pattern, "");
    }
    return result.replace(/\n{3,}/g, "\n\n").trim();
  }
}

// ============================================================================
// Factory
// ============================================================================

export function createPostToolHandler(config?: {
  postToolCommands?: string[];
  undercoverEnabled?: boolean;
}): PostToolHookHandler {
  return new PostToolHookHandler(config);
}
