/**
 * Undercover Mode for CLAWFORGE
 * 
 * Strips AI indicators from outputs so they look human-written.
 * Useful for clean commits, PR descriptions, code comments.
 * 
 * Works as a PostToolUse hook.
 */

// ============================================================================
// Patterns to Strip
// ============================================================================

const AI_INDICATORS = [
  /Generated by (Claude|GPT|AI|agent|model)/gi,
  /As an AI (assistant|model|agent)/gi,
  /I'm an AI/gi,
  /This (was|is) (auto-)?generated/gi,
  /\[ai-?generated\]/gi,
  /\[auto-?generated\]/gi,
  /\[generated by (claude|gpt|ai)\]/gi,
  /Created (by|with) (Claude|GPT|AI|Copilot)/gi,
  /Written (by|with) (Claude|GPT|AI|Copilot)/gi,
  /Powered by (Claude|GPT|AI)/gi,
];

// ============================================================================
// Sanitizer
// ============================================================================

/**
 * Strip AI indicators from text output.
 */
export function sanitizeOutput(text: string): string {
  let result = text;
  
  for (const pattern of AI_INDICATORS) {
    result = result.replace(pattern, "");
  }
  
  // Clean up double newlines left by removals
  result = result.replace(/\n{3,}/g, "\n\n");
  
  // Clean up leading/trailing whitespace on lines
  result = result
    .split("\n")
    .map(line => line.trimEnd())
    .join("\n");
  
  return result.trim();
}

/**
 * Sanitize a git commit message.
 */
export function sanitizeCommitMessage(message: string): string {
  let result = sanitizeOutput(message);
  
  // Remove common AI commit prefixes
  const prefixes = [
    /^(ai|claude|gpt|copilot|auto|agent):\s*/gi,
    /^\[ai\]\s*/gi,
    /^\[auto\]\s*/gi,
  ];
  
  for (const prefix of prefixes) {
    result = result.replace(prefix, "");
  }
  
  return result;
}

/**
 * Check if text contains AI indicators.
 */
export function containsAIIndicators(text: string): boolean {
  return AI_INDICATORS.some(pattern => pattern.test(text));
}

// ============================================================================
// Config
// ============================================================================

export interface UndercoverConfig {
  /** Whether undercover mode is enabled */
  enabled: boolean;
  /** Whether to sanitize commit messages */
  sanitizeCommits: boolean;
  /** Whether to sanitize code comments */
  sanitizeComments: boolean;
  /** Whether to sanitize PR descriptions */
  sanitizePRs: boolean;
}

export const DEFAULT_UNDERCOVER_CONFIG: UndercoverConfig = {
  enabled: true,
  sanitizeCommits: true,
  sanitizeComments: true,
  sanitizePRs: true,
};
