/**
 * CLAWFORGE Integration Test
 * 
 * Tests the full flow: Permission → Pool → Department → Forge → Train → Execute
 */

// Import our modules directly
import { PermissionPolicy, checkPermission } from "./src/security/permission-modes.js";
import { createToolHookRunner } from "./src/hooks/tool-hooks.js";
import { parseClawMd, renderClawMdPrompt } from "./src/agents/claw-md.js";
import { buildContinuationMessage } from "./src/agents/compaction-enhanced.js";
import { sanitizeOutput } from "./src/agents/undercover.js";
import { AgentPool, DEFAULT_POOL_CONFIG } from "./src/agents/agent-pool.js";
import { DepartmentManager } from "./src/agents/department.js";
import { TrainingManager } from "./src/agents/training-loop.js";
import { PatternMatcher } from "./src/agents/pattern-recognition.js";
import { BuddyManager } from "./src/agents/buddy.js";
import { ClawOrchestrator } from "./src/agents/claw-orchestrator.js";

async function runTests() {
  let passed = 0;
  let failed = 0;

  function test(name: string, fn: () => void | Promise<void>) {
    return Promise.resolve(fn()).then(() => {
      console.log(`✅ ${name}`);
      passed++;
    }).catch((e: Error) => {
      console.log(`❌ ${name}: ${e.message}`);
      failed++;
    });
  }

  function assert(condition: boolean, msg?: string) {
    if (!condition) throw new Error(msg || "Assertion failed");
  }

  console.log("=== CLAWFORGE Integration Test ===\n");

  // 1. Permission System
  await test("Permission: read-only allows reads", () => {
    const result = checkPermission("read-only", "file_read");
    assert(result.outcome === "allow");
  });

  await test("Permission: read-only denies writes", () => {
    const result = checkPermission("read-only", "file_write");
    assert(result.outcome === "deny");
  });

  await test("Permission: prompt mode asks for exec", () => {
    const result = checkPermission("prompt", "exec");
    assert(result.outcome === "prompt");
  });

  // 2. Tool Hooks
  await test("Tool Hooks: empty config allows", async () => {
    const runner = createToolHookRunner();
    const result = await runner.runPreToolUse("exec", "{}");
    assert(result.outcome === "allow");
  });

  // 3. CLAW.md
  await test("CLAW.md: parses instructions", () => {
    const content = "## Instructions\n- Use TypeScript\n- Write tests\n";
    const result = parseClawMd(content);
    assert(result.instructions.includes("Use TypeScript"));
  });

  // 4. Compaction
  await test("Compaction: continuation message", () => {
    const msg = buildContinuationMessage("User asked about auth.");
    assert(msg.includes("continued from a previous conversation"));
  });

  // 5. Undercover
  await test("Undercover: strips AI indicators", () => {
    const result = sanitizeOutput("Generated by Claude. The code is ready.");
    assert(!result.includes("Generated by Claude"));
  });

  // 6. Agent Pool
  await test("Agent Pool: creates 5 slots", () => {
    const pool = new AgentPool("/tmp/test-pool");
    const status = pool.getStatus();
    assert(status.total === 5, `Expected 5, got ${status.total}`);
    assert(status.idle === 5, `Expected 5 idle, got ${status.idle}`);
  });

  await test("Agent Pool: assign identity", () => {
    const pool = new AgentPool("/tmp/test-pool");
    const identity = { name: "Songwriter", emoji: "🎶", department: "Multimedia", clawMd: "Write songs", memoryDir: "memory/songwriter", permissionLevel: "prompt" };
    const slot = pool.assignIdentity(identity);
    assert(slot !== null, "Should get a slot");
    assert(slot!.busy === true, "Slot should be busy");
    assert(slot!.identity?.name === "Songwriter", "Identity should match");
  });

  await test("Agent Pool: release slot", () => {
    const pool = new AgentPool("/tmp/test-pool");
    const identity = { name: "Test", emoji: "🤖", department: "Test", clawMd: "Test", memoryDir: "memory/test", permissionLevel: "prompt" };
    const slot = pool.assignIdentity(identity);
    const released = pool.releaseSlot(slot!.id);
    assert(released === true, "Should release");
    assert(pool.getIdleSlots().length === 5, "All slots should be idle");
  });

  await test("Agent Pool: lock as production", () => {
    const pool = new AgentPool("/tmp/test-pool");
    const identity = { name: "Locked", emoji: "🔒", department: "Test", clawMd: "Locked", memoryDir: "memory/locked", permissionLevel: "prompt" };
    const slot = pool.assignIdentity(identity);
    pool.lockAsProduction(slot!.id);
    assert(slot!.type === "production", "Should be production");
    assert(pool.releaseSlot(slot!.id) === false, "Can't release production");
  });

  // 7. Department Manager
  await test("Department: create and find", async () => {
    const dept = new DepartmentManager("/tmp/test-dept");
    await dept.load();
    const created = dept.create("Multimedia", "Handles media tasks", "🎵");
    const found = dept.find("multimedia");
    assert(found !== null, "Should find department");
    assert(found!.name === "Multimedia", "Name should match");
  });

  await test("Department: add agent", async () => {
    const dept = new DepartmentManager("/tmp/test-dept");
    await dept.load();
    dept.create("Engineering", "Builds code", "💻");
    const added = dept.addAgent("engineering", "Developer");
    assert(added === true, "Should add agent");
    assert(dept.getAgents("engineering").includes("Developer"), "Agent should be in dept");
  });

  await test("Department: suggest department from task", () => {
    const dept = new DepartmentManager("/tmp/test-dept");
    const suggestion = dept.suggestDepartment("write a song about AI");
    assert(suggestion.name === "Multimedia", `Expected Multimedia, got ${suggestion.name}`);
    assert(suggestion.emoji === "🎵", "Should suggest 🎵");
  });

  // 8. Training Loop
  await test("Training: start and complete", async () => {
    const training = new TrainingManager("/tmp/test-training");
    await training.load();
    const session = training.startTraining("Songwriter", "Multimedia", "Write AI lyrics");
    assert(session.status === "in_progress", "Should be in progress");
    training.addIteration("Songwriter", "Draft 1", "Make it happier", "Updated tone");
    const completed = training.completeTraining("Songwriter");
    assert(completed!.status === "completed", "Should be completed");
    assert(training.isTrained("Songwriter") === true, "Should be trained");
  });

  // 9. Pattern Recognition
  await test("Pattern: classify tasks", async () => {
    const matcher = new PatternMatcher("/tmp/test-patterns");
    await matcher.load();
    const result = matcher.recordTask("research papers on AI");
    assert(result.found === false || result.confidence >= 0, "Should return routing result");
  });

  await test("Pattern: suggest persistent after 3", async () => {
    const matcher = new PatternMatcher("/tmp/test-patterns");
    await matcher.load();
    matcher.recordTask("research AI papers");
    matcher.recordTask("research ML papers");
    const r3 = matcher.recordTask("research deep learning");
    assert(r3.suggestPersistent === true, "Should suggest persistent after 3");
  });

  // 10. Buddy
  await test("Buddy: react to success", async () => {
    const buddy = new BuddyManager("/tmp/test-buddy");
    await buddy.load();
    const reaction = buddy.react("success");
    assert(reaction.state === "happy", "Should be happy");
    assert(reaction.emoji === "^_^", "Should have happy emoji");
  });

  // 11. Orchestrator (full flow)
  await test("Orchestrator: initialize", async () => {
    const orchestrator = new ClawOrchestrator({
      projectRoot: "/tmp/test",
      dataDir: "/tmp/test-orch",
      defaultPermissionMode: "prompt",
      poolSize: 5,
    });

    const pool = new AgentPool("/tmp/test-orch/pool");
    const departments = new DepartmentManager("/tmp/test-orch/dept");
    const training = new TrainingManager("/tmp/test-orch/training");
    const patterns = new PatternMatcher("/tmp/test-orch/patterns");
    const buddy = new BuddyManager("/tmp/test-orch/buddy");
    const policy = new PermissionPolicy({ mode: "prompt" });
    const hooks = createToolHookRunner();
    const clawMd = parseClawMd("## Instructions\n- Be helpful");

    await pool.load();
    await departments.load();
    await training.load();
    await patterns.load();
    await buddy.load();

    await orchestrator.initialize({
      permissionPolicy: policy,
      hookRunner: hooks,
      clawMd,
      pool,
      departments,
      training,
      patterns,
      buddy,
    });

    const status = orchestrator.getStatus();
    assert(status.includes("Pool"), "Status should include pool info");
    assert(status.includes("Buddy"), "Status should include buddy info");
  });

  await test("Orchestrator: process request", async () => {
    const orchestrator = new ClawOrchestrator({
      projectRoot: "/tmp/test",
      dataDir: "/tmp/test-orch2",
      defaultPermissionMode: "prompt",
      poolSize: 5,
    });

    const pool = new AgentPool("/tmp/test-orch2/pool");
    const departments = new DepartmentManager("/tmp/test-orch2/dept");
    const training = new TrainingManager("/tmp/test-orch2/training");
    const patterns = new PatternMatcher("/tmp/test-orch2/patterns");
    const buddy = new BuddyManager("/tmp/test-orch2/buddy");
    const policy = new PermissionPolicy({ mode: "prompt" });
    const hooks = createToolHookRunner();
    const clawMd = parseClawMd("## Instructions\n- Be helpful");

    await Promise.all([pool.load(), departments.load(), training.load(), patterns.load(), buddy.load()]);

    await orchestrator.initialize({
      permissionPolicy: policy, hookRunner: hooks, clawMd,
      pool, departments, training, patterns, buddy,
    });

    const result = await orchestrator.processRequest("write a song about AI");
    assert(result.action === "forge", "New task should trigger forge");
  });

  await test("Orchestrator: forge agent", async () => {
    const orchestrator = new ClawOrchestrator({
      projectRoot: "/tmp/test",
      dataDir: "/tmp/test-orch3",
      defaultPermissionMode: "prompt",
      poolSize: 5,
    });

    const pool = new AgentPool("/tmp/test-orch3/pool");
    const departments = new DepartmentManager("/tmp/test-orch3/dept");
    const training = new TrainingManager("/tmp/test-orch3/training");
    const patterns = new PatternMatcher("/tmp/test-orch3/patterns");
    const buddy = new BuddyManager("/tmp/test-orch3/buddy");
    const policy = new PermissionPolicy({ mode: "prompt" });
    const hooks = createToolHookRunner();
    const clawMd = parseClawMd("## Instructions\n- Be helpful");

    await Promise.all([pool.load(), departments.load(), training.load(), patterns.load(), buddy.load()]);

    await orchestrator.initialize({
      permissionPolicy: policy, hookRunner: hooks, clawMd,
      pool, departments, training, patterns, buddy,
    });

    const result = await orchestrator.forge({
      userRequest: "write a song about AI",
      requirements: "Write a song: Alternative rock, upbeat, 3 verses + chorus, Radiohead style",
    });

    assert(result.success === true, "Forge should succeed");
    assert(result.department !== null, "Should have department");
    assert(result.slot !== null, "Should have agent slot");
    assert(result.slot!.identity?.name === "Songwriter", "Should name agent Songwriter");
    assert(result.messages.some(m => m.includes("Songwriter")), "Messages should mention Songwriter");
  });

  // Results
  console.log(`\n=== Results: ${passed} passed, ${failed} failed ===`);
  process.exit(failed > 0 ? 1 : 0);
}

runTests();
